controller_list:
  - name: fake_GropoBrazo_controller
    type: $(arg fake_execution_type)
    joints:
      - Hombro
      - Brazo
      - Antebrazo
      - Munieca
      - Mano
      - Dedo
  - name: fake_GrupoDedo_controller
    type: $(arg fake_execution_type)
    joints:
      - Garra1
      - Garra2
initial:  # Define initial robot poses per group
  - group: GropoBrazo
    pose: Zero
  - group: GrupoDedo
    pose: DedoAbierto