GropoBrazo_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Hombro
    - Brazo
    - Antebrazo
    - Munieca
    - Mano
    - Dedo
  gains:
    Hombro:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Brazo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Antebrazo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Munieca:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Mano:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Dedo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
GrupoDedo_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Garra1
    - Garra2
  gains:
    Garra1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Garra2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1