controller_list:
  - name: GropoBrazo_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Hombro
      - Brazo
      - Antebrazo
      - Munieca
      - Mano
      - Dedo
  - name: GrupoDedo_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Garra1
      - Garra2